// PFP Slide Preview Component
// Renders slides generated by the PRICE-FOR-PROFIT bundle
// Supports flexible content structure defined by PFP's skill file

import { Slide } from '../types';

interface PFPSlidePreviewProps {
  slide: Slide;
  isSelected?: boolean;
  onClick?: () => void;
}

export function PFPSlidePreview({ slide, isSelected, onClick }: PFPSlidePreviewProps) {
  return (
    <div
      onClick={onClick}
      className="relative w-full aspect-[16/9] rounded-lg border-2 transition-all cursor-pointer overflow-hidden bg-white"
      style={{
        borderColor: isSelected ? '#E8610A' : '#E5E7EB',
        boxShadow: isSelected ? '0 0 0 3px rgba(232, 97, 10, 0.1)' : 'none',
      }}
    >
      {/* Slide Header */}
      <div
        className="px-6 py-4 border-b"
        style={{ backgroundColor: '#F9FAFB', borderColor: '#E5E7EB' }}
      >
        <h2 className="text-xl font-bold" style={{ color: '#1F2937' }}>
          {slide.title}
        </h2>
        {slide.description && (
          <p className="text-sm mt-1" style={{ color: '#6B7280' }}>
            {slide.description}
          </p>
        )}
      </div>

      {/* Slide Content - Flexible rendering based on content field */}
      <div className="p-6">
        {slide.content ? (
          <PFPContentRenderer content={slide.content} />
        ) : (
          <div className="text-center py-12" style={{ color: '#9CA3AF' }}>
            <p>No content to display</p>
          </div>
        )}
      </div>

      {/* Bundle Badge */}
      <div
        className="absolute top-2 right-2 px-2 py-1 rounded text-xs font-medium"
        style={{ backgroundColor: '#E8610A', color: 'white' }}
      >
        PFP
      </div>
    </div>
  );
}

/**
 * Renders PFP content structure
 * This is a flexible renderer that adapts to whatever structure PFP returns
 */
function PFPContentRenderer({ content }: { content: any }) {
  // If content has sections array (narrative structure)
  if (content.sections && Array.isArray(content.sections)) {
    return (
      <div className="space-y-4">
        {content.sections.map((section: any, idx: number) => (
          <div key={idx} className="border-l-4 pl-4" style={{ borderColor: '#E8610A' }}>
            {section.heading && (
              <h3 className="font-bold text-lg mb-2" style={{ color: '#1F2937' }}>
                {section.heading}
              </h3>
            )}
            {section.content && (
              <p className="text-sm" style={{ color: '#4B5563' }}>
                {section.content}
              </p>
            )}
            {section.bullets && Array.isArray(section.bullets) && (
              <ul className="list-disc list-inside mt-2 space-y-1">
                {section.bullets.map((bullet: string, bidx: number) => (
                  <li key={bidx} className="text-sm" style={{ color: '#4B5563' }}>
                    {bullet}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </div>
    );
  }

  // If content has a body field (simple text content)
  if (content.body) {
    return (
      <div className="prose prose-sm max-w-none" style={{ color: '#4B5563' }}>
        {typeof content.body === 'string' ? (
          <p>{content.body}</p>
        ) : (
          <pre className="whitespace-pre-wrap">{JSON.stringify(content.body, null, 2)}</pre>
        )}
      </div>
    );
  }

  // If content has points array (bullet list)
  if (content.points && Array.isArray(content.points)) {
    return (
      <ul className="list-disc list-inside space-y-2">
        {content.points.map((point: string, idx: number) => (
          <li key={idx} className="text-sm" style={{ color: '#4B5563' }}>
            {point}
          </li>
        ))}
      </ul>
    );
  }

  // Fallback: render raw JSON for debugging
  return (
    <div className="p-4 rounded" style={{ backgroundColor: '#F3F4F6' }}>
      <p className="text-xs font-mono" style={{ color: '#6B7280' }}>
        <pre className="whitespace-pre-wrap">{JSON.stringify(content, null, 2)}</pre>
      </p>
    </div>
  );
}
