import pptxgen from 'pptxgenjs';
import { Slide, DeckTheme, BrandColor, getSlideComponents } from '../types';
import { DECK_THEME } from '../constants';
import { compose, computeCardLayout, LayoutRect, BODY_W, BODY_LEFT, CARD_GUTTER, MAX_CARD_W, CALLOUT_Y } from './composition-engine';

export function generatePowerPoint(slides: Slide[], theme: DeckTheme = DECK_THEME): void {
  const pptx = new pptxgen();

  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'Emma\'s Awesome PPT Generator';
  pptx.title = 'INSIGHT2PROFIT Presentation';
  pptx.subject = 'Generated by Emma\'s Awesome PPT Generator';

  pptx.defineLayout({ name: 'EXEC_WIDE', width: theme.slideSize.width, height: theme.slideSize.height });
  pptx.layout = 'EXEC_WIDE';

  slides.forEach((slide) => renderSlide(pptx, slide, theme));

  pptx.writeFile({ fileName: 'INSIGHT2PROFIT_Presentation.pptx' });
}

// ─── SLIDE RENDERER ───────────────────────────────────────────

function renderSlide(pptx: pptxgen, slide: Slide, t: DeckTheme) {
  const s = pptx.addSlide();
  s.background = { color: t.colors.lt1 };

  // Check if this is a special direction_proof slide type
  const slideData = slide as any;
  if (slideData.type === 'direction_proof') {
    renderDirectionProofSlide(s, slideData, t);
    addFooter(s, t);
    return;
  }

  const contentStartY = addTitleWithDivider(s, slide, t);

  // Composition engine: template-driven grid layout
  const layout = compose(slide.templateId, slide.slotContent, slide.calloutBar);

  // Render each component at its computed position
  const allComponents = getSlideComponents(slide);
  for (const comp of allComponents) {
    const region = layout.get(comp.id);
    if (!region) continue;

    switch (comp.type) {
      case 'bullet_list': renderBulletList(s, comp, region, t); break;
      case 'stat_hero': renderStatHero(s, comp, region, t); break;
      case 'kpi_cards': renderKpiCards(s, comp, region, t); break;
      case 'icon_columns': renderIconColumns(s, comp, region, t); break;
      case 'process_flow': renderProcessFlow(s, comp, region, t); break;
      case 'data_table': renderDataTable(s, comp, region, t); break;
      case 'simple_table': renderSimpleTable(s, comp, region, t); break;
      case 'chart': renderChart(pptx, s, comp, region, t); break;
      case 'callout_bar': renderCalloutBar(s, comp, region, t); break;
      case 'timeline_track': renderTimelineTrack(s, comp, region, t); break;
      case 'icon_grid': renderIconGrid(s, comp, region, t); break;
      case 'screenshot': renderScreenshot(s, comp, region, t); break;
      case 'text_block': renderTextBlock(s, comp, region, t); break;
      case 'comparison_bars': renderComparisonBars(s, comp, region, t); break;
      case 'team_structure': renderTeamStructure(s, comp, region, t); break;
      case 'waterfall_chart': renderWaterfallChart(s, comp, region, t); break;
      case 'context_banner': renderContextBanner(s, comp, region, t); break;
      default:
        // Fallback for unrecognized component types
        console.warn(`Unknown component type: ${comp.type} — rendering as bullet_list fallback`);
        renderBulletList(s, comp, region, t);
        break;
    }
  }

  addFooter(s, t);
}

// ─── COMMON HELPERS ───────────────────────────────────────────

function addFooter(s: any, t: DeckTheme) {
  s.addShape('rect', { x: 0.75, y: 6.85, w: 11.833, h: 0.015, fill: { color: t.colors.accent1 }, line: { type: 'none' } });
  s.addText('INSIGHT2PROFIT', { x: 0.75, y: 6.95, w: 2.0, h: 0.3, fontSize: 10, color: t.colors.dk1, fontFace: 'Calibri', align: 'left', valign: 'middle', bold: true });
  s.addText('1', { x: 11.0, y: 6.95, w: 1.583, h: 0.3, fontSize: 10, color: t.colors.accent1, fontFace: 'Calibri', align: 'right', valign: 'middle' });
}

function addTitleWithDivider(s: any, slide: Slide, t: DeckTheme, y: number = 0.6) {
  const title = slide.title;
  const parts = title.split('|').map(p => p.trim());
  const boldPart = parts[0] || title;
  const regularPart = parts[1] || '';

  // Dynamic font size based on title length to prevent overflow
  const totalLength = title.length;
  let fontSize = 24;
  if (totalLength > 80) {
    fontSize = 16;
  } else if (totalLength > 60) {
    fontSize = 18;
  }

  let currentY = y;

  // Render title
  if (regularPart) {
    s.addText([
      { text: boldPart, options: { bold: true, color: t.colors.dk1, fontSize } },
      { text: ' | ', options: { color: t.colors.dk1, fontSize } },
      { text: regularPart, options: { color: t.colors.dk1, fontSize } }
    ], {
      x: 0.75,
      y: currentY,
      w: 11.833,
      h: 0.45,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });
  } else {
    s.addText(boldPart, {
      x: 0.75,
      y: currentY,
      w: 11.833,
      h: 0.45,
      fontSize,
      bold: true,
      color: t.colors.dk1,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });
  }

  currentY += 0.5;

  // Render key metric
  if (slide.keyMetric) {
    s.addText(slide.keyMetric, {
      x: 0.75,
      y: currentY,
      w: 11.833,
      h: 0.5,
      fontSize: 36,
      bold: true,
      color: t.colors.accent3,  // Teal
      fontFace: 'Calibri',
      align: 'center',
      valign: 'middle'
    });

    currentY += 0.55;

    if (slide.keyMetricLabel) {
      s.addText(slide.keyMetricLabel, {
        x: 0.75,
        y: currentY,
        w: 11.833,
        h: 0.3,
        fontSize: 14,
        color: t.colors.accent1,  // Gray
        fontFace: 'Calibri',
        align: 'center',
        valign: 'top'
      });

      currentY += 0.35;
    }
  }

  // Divider line
  s.addShape('rect', {
    x: 0.75,
    y: currentY,
    w: 11.833,
    h: 0.02,
    fill: { color: t.colors.accent1 },
    line: { type: 'none' }
  });

  // Return the Y position after title area for content positioning
  return currentY + 0.05;
}

function addDirectionBanner(s: any, leftText: string, rightText: string, t: DeckTheme) {
  // Left side - Navy rectangle
  s.addShape('rect', { 
    x: 0.75, 
    y: 1.4, 
    w: 7.0, 
    h: 0.5, 
    fill: { color: t.colors.dk1 }, // Navy #002F4A
    line: { type: 'none' } 
  });
  s.addText(leftText, { 
    x: 0.75, 
    y: 1.4, 
    w: 7.0, 
    h: 0.5, 
    fontSize: 12, 
    bold: true, 
    color: 'FFFFFF', 
    fontFace: 'Calibri', 
    align: 'center', 
    valign: 'middle' 
  });

  // Arrow connector - Chevron pointing right
  s.addShape('triangle', {
    x: 7.75,
    y: 1.4,
    w: 0.4,
    h: 0.5,
    fill: { color: t.colors.dk1 }, // Navy
    line: { type: 'none' },
    flipH: false,
    rotate: 90
  });

  // Right side - Teal rectangle
  s.addShape('rect', { 
    x: 8.15, 
    y: 1.4, 
    w: 4.383, 
    h: 0.5, 
    fill: { color: t.colors.accent3 }, // Teal #1B6B7B
    line: { type: 'none' } 
  });
  s.addText(rightText, { 
    x: 8.15, 
    y: 1.4, 
    w: 4.383, 
    h: 0.5, 
    fontSize: 12, 
    bold: true, 
    color: 'FFFFFF', 
    fontFace: 'Calibri', 
    align: 'center', 
    valign: 'middle' 
  });
}

function getColorHex(colorName: BrandColor | undefined, t: DeckTheme): string {
  switch (colorName) {
    case 'navy': return t.colors.dk1;
    case 'teal': return t.colors.accent3;
    case 'orange': return t.colors.accent2;
    default: return t.colors.dk1;
  }
}

// ─── COMPONENT RENDERERS ──────────────────────────────────────

function renderBulletList(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const color = getColorHex(comp.bulletColor, t);
  if (comp.heading) {
    s.addText(comp.heading, { x: r.x, y: r.y, w: r.w, h: 0.35, fontSize: 14, bold: true, color: t.colors.dk1, fontFace: 'Calibri', align: 'left', valign: 'middle' });
  }
  const headingOffset = comp.heading ? 0.4 : 0;
  const bullets = (comp.items || []).slice(0, 8).map((b: string) => ({ text: b, options: {} }));
  if (bullets.length > 0) {
    s.addText(bullets, { x: r.x + 0.2, y: r.y + headingOffset, w: r.w - 0.4, h: r.h - headingOffset, fontSize: 14, color: t.colors.dk1, fontFace: 'Calibri', bullet: { type: 'bullet', characterCode: '2022', color }, lineSpacing: 18, valign: 'top' });
  }
}

function renderStatHero(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const color = getColorHex(comp.accentColor || 'navy', t);
  const displayValue = comp.value || '-';
  const hasBaseline = comp.baseline || comp.comparisonLabel;

  if (hasBaseline) {
    // Compact layout: value (45%) → label (15%) → baseline (15%) → supporting (25%)
    s.addText(displayValue, { x: r.x, y: r.y, w: r.w, h: r.h * 0.45, fontSize: 56, bold: true, color, fontFace: 'Calibri', align: 'center', valign: 'bottom' });
    s.addText(comp.label || '', { x: r.x, y: r.y + r.h * 0.45, w: r.w, h: r.h * 0.15, fontSize: 14, bold: true, color: t.colors.accent3, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    // Baseline/comparison line
    const baselineText = comp.baseline || comp.comparisonLabel || '';
    s.addText(baselineText, { x: r.x + 0.3, y: r.y + r.h * 0.60, w: r.w - 0.6, h: r.h * 0.15, fontSize: 11, italic: true, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    if (comp.supportingText) {
      s.addText(comp.supportingText, { x: r.x + 0.5, y: r.y + r.h * 0.75, w: r.w - 1, h: r.h * 0.25, fontSize: 11, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'top' });
    }
  } else {
    // Original layout
    s.addText(displayValue, { x: r.x, y: r.y, w: r.w, h: r.h * 0.55, fontSize: 64, bold: true, color, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(comp.label || '', { x: r.x, y: r.y + r.h * 0.55, w: r.w, h: r.h * 0.2, fontSize: 16, bold: true, color: t.colors.accent3, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    if (comp.supportingText) {
      s.addText(comp.supportingText, { x: r.x + 1, y: r.y + r.h * 0.75, w: r.w - 2, h: r.h * 0.25, fontSize: 12, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'top' });
    }
  }
}

function renderKpiCards(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const metrics = comp.metrics || [];
  if (metrics.length === 0) return;
  const cards = computeCardLayout(metrics.length, r.x, r.w, CARD_GUTTER, MAX_CARD_W);
  metrics.forEach((metric: any, i: number) => {
    const { x, w: cardW } = cards[i];
    s.addShape('rect', { x, y: r.y, w: cardW, h: r.h, fill: { color: t.colors.lt2 }, line: { type: 'none' } });
    s.addText(metric.value, { x, y: r.y + r.h * 0.15, w: cardW, h: r.h * 0.4, fontSize: 32, bold: true, color: t.colors.dk1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(metric.label, { x, y: r.y + r.h * 0.6, w: cardW, h: r.h * 0.25, fontSize: 11, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    if (metric.trend) {
      // Replace arrow emojis with text for PowerPoint compatibility
      const trendIcon = metric.trend === 'up' ? '^' : metric.trend === 'down' ? 'v' : '-';
      const trendColor = metric.trend === 'up' ? t.colors.accent3 : metric.trend === 'down' ? t.colors.accent5 : t.colors.accent1;
      s.addText(trendIcon, { x: x + cardW - 0.4, y: r.y + 0.05, w: 0.35, h: 0.35, fontSize: 18, bold: true, color: trendColor, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    }
  });
}

function renderIconColumns(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const columns = comp.columns || [];
  if (columns.length === 0) return;

  // Section label above columns (e.g., "HOW IT ELIMINATES DELAYS")
  let contentStartY = r.y;
  if (comp.sectionLabel) {
    const labelColor = getColorHex(comp.sectionLabelColor || 'teal', t);
    s.addText(comp.sectionLabel.toUpperCase(), {
      x: r.x, y: r.y, w: r.w, h: 0.3,
      fontSize: 10, bold: true, color: labelColor, fontFace: 'Calibri',
      align: 'left', valign: 'middle', letterSpacing: 1.5
    });
    contentStartY = r.y + 0.3;
  }

  const adjustedH = r.h - (contentStartY - r.y);
  const cards = computeCardLayout(columns.length, r.x, r.w, CARD_GUTTER, MAX_CARD_W);
  columns.forEach((col: any, i: number) => {
    const { x, w: colW } = cards[i];
    const headerColor = getColorHex(col.headerColor, t);
    const isHighlighted = col.highlighted === true;
    const useIconCircle = col.iconCircle === true;
    const headerBarH = isHighlighted ? 0.65 : 0.55;

    // Header bar
    s.addShape('rect', { x, y: contentStartY, w: colW, h: headerBarH, fill: { color: headerColor } });

    // Icon: circle background or plain
    const iconText = col.icon || '\u2022';
    if (useIconCircle) {
      const circleSize = 0.38;
      const circleX = x + 0.08;
      const circleY = contentStartY + (headerBarH - circleSize) / 2;
      s.addShape('ellipse', {
        x: circleX, y: circleY, w: circleSize, h: circleSize,
        fill: { color: 'FFFFFF', transparency: 75 },
        line: { type: 'none' }
      });
      s.addText(iconText, { x: circleX, y: circleY, w: circleSize, h: circleSize, fontSize: 16, color: t.colors.lt1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
      s.addText(col.header, { x: x + 0.52, y: contentStartY, w: colW - 0.62, h: headerBarH, fontSize: isHighlighted ? 14 : 13, bold: true, color: t.colors.lt1, fontFace: 'Calibri', align: 'left', valign: 'middle' });
    } else {
      s.addText(iconText, { x: x + 0.1, y: contentStartY + 0.08, w: 0.4, h: 0.4, fontSize: isHighlighted ? 18 : 16, color: t.colors.lt1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
      s.addText(col.header, { x: x + 0.55, y: contentStartY, w: colW - 0.65, h: headerBarH, fontSize: isHighlighted ? 14 : 13, bold: true, color: t.colors.lt1, fontFace: 'Calibri', align: 'left', valign: 'middle' });
    }

    // Badge rendering (numbered circles above columns)
    if (col.badge) {
      const badgeSize = 0.35;
      const badgeX = col.badgePosition === 'top-center'
        ? x + colW / 2 - badgeSize / 2
        : x + 0.1;
      const badgeY = contentStartY - 0.4;
      s.addShape('ellipse', {
        x: badgeX, y: badgeY, w: badgeSize, h: badgeSize,
        fill: { color: headerColor },
        line: { color: t.colors.lt1, width: 2 }
      });
      s.addText(col.badge, {
        x: badgeX, y: badgeY, w: badgeSize, h: badgeSize,
        fontSize: 18, bold: true, color: t.colors.lt1,
        fontFace: 'Calibri', align: 'center', valign: 'middle'
      });
    }

    const contentY = contentStartY + headerBarH;
    const contentH = adjustedH - headerBarH;

    // Content background
    s.addShape('rect', { x, y: contentY, w: colW, h: contentH, fill: { color: isHighlighted ? 'EDF6F7' : t.colors.lt2 }, line: { type: 'none' } });

    // Highlighted border (left, right, bottom)
    if (isHighlighted) {
      const borderW = 0.03;
      s.addShape('rect', { x, y: contentY, w: borderW, h: contentH, fill: { color: headerColor }, line: { type: 'none' } });
      s.addShape('rect', { x: x + colW - borderW, y: contentY, w: borderW, h: contentH, fill: { color: headerColor }, line: { type: 'none' } });
      s.addShape('rect', { x, y: contentY + contentH - borderW, w: colW, h: borderW, fill: { color: headerColor }, line: { type: 'none' } });
    }

    // Content items — support titled details or plain strings
    const items = (col.items || []).slice(0, 5);
    let cursorY = contentY + 0.1;
    const itemPadX = 0.15;
    const itemW = colW - 0.3;

    const hasTitledItems = items.some((item: any) => typeof item === 'object' && item.title);

    if (hasTitledItems) {
      // Rich titled-detail rendering
      items.forEach((item: any) => {
        if (typeof item === 'object' && item.title) {
          // Bold title
          s.addText(item.title, {
            x: x + itemPadX, y: cursorY, w: itemW, h: 0.22,
            fontSize: 11, bold: true, color: t.colors.dk1, fontFace: 'Calibri',
            align: 'left', valign: 'top'
          });
          cursorY += 0.20;
          // Detail text (lighter)
          if (item.detail) {
            s.addText(item.detail, {
              x: x + itemPadX, y: cursorY, w: itemW, h: 0.28,
              fontSize: 10, color: t.colors.accent1, fontFace: 'Calibri',
              align: 'left', valign: 'top', lineSpacing: 12
            });
            cursorY += 0.28;
          }
          cursorY += 0.06; // gap between items
        } else {
          // Plain string fallback within mixed list
          const text = typeof item === 'string' ? item : item.title || '';
          s.addText([{ text, options: {} }], {
            x: x + itemPadX, y: cursorY, w: itemW, h: 0.22,
            fontSize: 11, color: t.colors.dk1, fontFace: 'Calibri',
            bullet: { type: 'bullet', characterCode: '2022', color: headerColor },
            valign: 'top'
          });
          cursorY += 0.24;
        }
      });
    } else {
      // Legacy plain string bullets
      const bullets = items.map((b: any) => ({ text: typeof b === 'string' ? b : b.title || '', options: {} }));
      if (bullets.length > 0) {
        s.addText(bullets, { x: x + itemPadX, y: cursorY, w: itemW, h: contentH - 0.2, fontSize: 12, color: t.colors.dk1, fontFace: 'Calibri', bullet: { type: 'bullet', characterCode: '2022', color: headerColor }, lineSpacing: 14, valign: 'top' });
      }
    }

    // Divider line between items and result section
    if (col.showDivider && col.resultLabel) {
      const dividerY = contentY + contentH * 0.6;
      s.addShape('line', {
        x, y: dividerY, w: colW, h: 0,
        line: { color: t.colors.accent1, width: 0.5, dashType: 'dash' }
      });
    }

    // Result section at bottom of column
    if (col.resultLabel) {
      const resultStartY = contentY + contentH * 0.62;
      // "THE RESULT" label
      s.addText(col.resultLabel.toUpperCase(), {
        x: x + itemPadX, y: resultStartY, w: itemW, h: 0.2,
        fontSize: 8, bold: true, color: headerColor, fontFace: 'Calibri',
        align: 'left', valign: 'middle', letterSpacing: 1.5
      });
      // Result value (big)
      if (col.resultValue) {
        s.addText(col.resultValue, {
          x: x + itemPadX, y: resultStartY + 0.2, w: itemW, h: 0.3,
          fontSize: 22, bold: true, color: t.colors.dk1, fontFace: 'Calibri',
          align: 'left', valign: 'middle'
        });
      }
      // Result detail (comparison text)
      if (col.resultDetail) {
        s.addText(col.resultDetail, {
          x: x + itemPadX, y: resultStartY + 0.48, w: itemW, h: 0.2,
          fontSize: 9, italic: true, color: t.colors.accent1, fontFace: 'Calibri',
          align: 'left', valign: 'top'
        });
      }
    }
  });
}

function renderProcessFlow(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const stages = comp.stages || [];
  if (stages.length === 0) return;
  const stageW = r.w / stages.length;

  // Calculate max arrow height (some stages may be highlighted and taller)
  const maxArrowH = stages.some((st: any) => st.highlighted) ? 0.7 : 0.55;
  const contentH = r.h - maxArrowH - 0.15; // Remaining height for content boxes

  // Stage colors cycle: navy, teal, orange, blue, back to navy
  const getStageColor = (i: number, stage: any): string => {
    // If stage is highlighted and has accentColor, use it
    if (stage.highlighted && stage.accentColor) {
      const colorMap: Record<string, string> = {
        'navy': t.colors.dk1,
        'teal': t.colors.accent3,
        'orange': t.colors.accent2
      };
      return colorMap[stage.accentColor] || t.colors.accent2;
    }
    // Otherwise use default color rotation
    const colors = [t.colors.dk1, t.colors.accent3, t.colors.accent2, '4472C4'];
    return colors[i % colors.length];
  };

  stages.forEach((stage: any, i: number) => {
    const x = r.x + i * stageW;
    const stageColor = getStageColor(i, stage);
    const isHighlighted = stage.highlighted === true;
    const arrowH = isHighlighted ? 0.7 : 0.55;
    const fontSize = isHighlighted ? 13 : 11;

    // First stage uses 'homePlate', others use 'chevron'
    const shapeType = i === 0 ? 'homePlate' : 'chevron';

    // Overlap each stage by 0.15" so chevrons connect
    const overlapX = i === 0 ? x : x - 0.15;
    const overlapW = i === 0 ? stageW - 0.1 : stageW + 0.05;

    // Timeframe label above arrow (10pt gray)
    if (stage.timeframe) {
      s.addText(stage.timeframe, {
        x,
        y: r.y - 0.35,
        w: stageW,
        h: 0.3,
        fontSize: 10,
        color: '808080',
        fontFace: 'Calibri',
        align: 'center',
        valign: 'middle'
      });
    }

    // Native PowerPoint shape (homePlate or chevron)
    s.addShape(shapeType, {
      x: overlapX,
      y: r.y,
      w: overlapW,
      h: arrowH,
      fill: { color: stageColor },
      line: { type: 'none' },
      shadow: isHighlighted ? { type: 'outer', blur: 8, offset: 2, angle: 90, opacity: 0.3 } : undefined
    });

    // Stage label (white text on top of shape)
    s.addText(stage.label, {
      x: overlapX + 0.1,
      y: r.y,
      w: overlapW - 0.2,
      h: arrowH,
      fontSize,
      bold: true,
      color: 'FFFFFF',
      fontFace: 'Calibri',
      align: 'center',
      valign: 'middle',
      wrap: true,
      shrinkText: true
    });

    // Content box below arrow
    const contentY = r.y + maxArrowH + 0.15;
    const contentBoxColor = isHighlighted ? 'EDF5F7' : t.colors.lt2;
    const contentBorder = isHighlighted ? { type: 'solid', color: '1B6B7B', pt: 2 } : { type: 'none' };

    s.addShape('rect', {
      x,
      y: contentY,
      w: stageW - 0.1,
      h: contentH,
      fill: { color: contentBoxColor },
      line: contentBorder
    });

    // Bullets in content box
    const bulletColor = isHighlighted ? '1B6B7B' : t.colors.dk1;
    const bullets = (stage.items || []).slice(0, 4).map((b: string) => ({ text: b, options: {} }));
    if (bullets.length > 0) {
      s.addText(bullets, {
        x: x + 0.15,
        y: contentY + 0.1,
        w: stageW - 0.4,
        h: contentH - 0.2,
        fontSize: 11,
        color: t.colors.dk1,
        fontFace: 'Calibri',
        bullet: { type: 'bullet', characterCode: '2022', color: bulletColor },
        lineSpacing: 13,
        valign: 'top'
      });
    }
  });
}

function renderDataTable(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const rowLabels = comp.rowLabels || [];
  const columns = comp.columns || [];
  const colCount = columns.length + 1;
  const colW = r.w / colCount;
  const rowH = Math.min(0.5, r.h / (rowLabels.length + 1));
  columns.forEach((col: any, ci: number) => {
    const x = r.x + (ci + 1) * colW;
    const bgColor = col.highlight ? t.colors.accent4 : t.colors.dk1;
    s.addShape('rect', { x, y: r.y, w: colW, h: rowH, fill: { color: bgColor }, line: { type: 'none' } });
    s.addText(col.header, { x, y: r.y, w: colW, h: rowH, fontSize: 12, bold: true, color: t.colors.lt1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
  });
  rowLabels.forEach((label: string, ri: number) => {
    const y = r.y + (ri + 1) * rowH;
    const bgColor = ri % 2 === 0 ? t.colors.lt1 : t.colors.accent6;
    s.addShape('rect', { x: r.x, y, w: colW, h: rowH, fill: { color: bgColor }, line: { color: t.colors.accent1, width: 0.5 } });
    s.addText(label, { x: r.x + 0.1, y, w: colW - 0.2, h: rowH, fontSize: 11, bold: true, color: t.colors.dk1, fontFace: 'Calibri', align: 'left', valign: 'middle' });
    columns.forEach((col: any, ci: number) => {
      const x = r.x + (ci + 1) * colW;
      const val = col.rows[ri] || '';
      s.addShape('rect', { x, y, w: colW, h: rowH, fill: { color: bgColor }, line: { color: t.colors.accent1, width: 0.5 } });
      // Replace checkmark/X unicode with Y/N for PowerPoint compatibility
      const isCheck = val === '\u2713' || val.toLowerCase() === 'yes';
      const isX = val === '\u2717' || val.toLowerCase() === 'no';
      const displayVal = isCheck ? 'Y' : isX ? 'N' : val;
      s.addText(displayVal, { x, y, w: colW, h: rowH, fontSize: isCheck || isX ? 14 : 11, bold: isCheck || isX, color: isCheck ? t.colors.accent3 : isX ? t.colors.accent5 : t.colors.dk1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    });
  });
}

function renderSimpleTable(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const headers = comp.headers || [];
  const rows = comp.rows || [];
  const title = comp.title;

  if (headers.length === 0 || rows.length === 0) return;

  const colCount = headers.length + 1; // +1 for the label column
  const colW = r.w / colCount;

  const titleH = title ? 0.25 : 0;
  const headerH = 0.35;
  const rowH = 0.35;

  // Smaller font for dense tables (4+ rows)
  const fontSize = rows.length >= 4 ? 10 : 11;

  let currentY = r.y;

  // Render title if present
  if (title) {
    s.addShape('rect', {
      x: r.x,
      y: currentY,
      w: r.w,
      h: titleH,
      fill: { color: t.colors.lt2 },
      line: { color: t.colors.accent1, width: 0.5 }
    });
    s.addText(title, {
      x: r.x + 0.1,
      y: currentY,
      w: r.w - 0.2,
      h: titleH,
      fontSize: 14,
      bold: true,
      color: t.colors.dk1,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });
    currentY += titleH;
  }

  // Render header row
  // First header cell (empty - above row labels)
  s.addShape('rect', {
    x: r.x,
    y: currentY,
    w: colW,
    h: headerH,
    fill: { color: t.colors.lt2 },
    line: { color: t.colors.accent1, width: 1.5 }
  });

  // Column headers
  headers.forEach((header: string, i: number) => {
    const x = r.x + (i + 1) * colW;
    s.addShape('rect', {
      x,
      y: currentY,
      w: colW,
      h: headerH,
      fill: { color: t.colors.lt2 },
      line: { color: t.colors.accent1, width: 1.5 }
    });
    s.addText(header, {
      x,
      y: currentY,
      w: colW,
      h: headerH,
      fontSize: 12,
      bold: true,
      color: t.colors.dk1,
      fontFace: 'Calibri',
      align: 'center',
      valign: 'middle'
    });
  });

  currentY += headerH;

  // Render data rows
  rows.forEach((row: any, ri: number) => {
    const bgColor = ri % 2 === 0 ? t.colors.lt1 : t.colors.accent6;

    // Row label
    s.addShape('rect', {
      x: r.x,
      y: currentY,
      w: colW,
      h: rowH,
      fill: { color: bgColor },
      line: { color: t.colors.accent1, width: 0.5 }
    });
    s.addText(row.label || '', {
      x: r.x + 0.1,
      y: currentY,
      w: colW - 0.2,
      h: rowH,
      fontSize,
      bold: true,
      color: t.colors.dk1,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });

    // Row values
    (row.values || []).forEach((val: string, vi: number) => {
      const x = r.x + (vi + 1) * colW;
      s.addShape('rect', {
        x,
        y: currentY,
        w: colW,
        h: rowH,
        fill: { color: bgColor },
        line: { color: t.colors.accent1, width: 0.5 }
      });
      s.addText(val || '', {
        x,
        y: currentY,
        w: colW,
        h: rowH,
        fontSize,
        color: t.colors.dk1,
        fontFace: 'Calibri',
        align: 'center',
        valign: 'middle'
      });
    });

    currentY += rowH;
  });
}

function renderChart(pptx: pptxgen, s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const data = comp.data || [];
  if (data.length === 0) return;
  const labels = data.map((d: any) => d.label);
  const values = data.map((d: any) => d.value);
  const chartType = comp.chartType === 'line' ? pptx.ChartType.line : pptx.ChartType.bar;

  // Configure chart options with axis titles
  const chartOptions: any = {
    x: r.x,
    y: r.y,
    w: r.w,
    h: r.h,
    showValue: true,
    valueFontSize: 10,
    catAxisLabelFontSize: 10,
    valAxisLabelFontSize: 10,
    chartColors: [t.colors.dk1],
    showLegend: false
  };

  // Add axis titles if provided
  if (comp.xAxisTitle) {
    chartOptions.catAxisTitle = comp.xAxisTitle;
    chartOptions.catAxisTitleFontSize = 11;
    chartOptions.catAxisTitleColor = t.colors.dk1;
  }

  if (comp.yAxisTitle) {
    chartOptions.valAxisTitle = comp.yAxisTitle;
    chartOptions.valAxisTitleFontSize = 11;
    chartOptions.valAxisTitleColor = t.colors.dk1;
    chartOptions.valAxisTitleRotate = 90;  // Vertical Y-axis title
  }

  s.addChart(chartType, [{ name: 'Value', labels, values }], chartOptions);
}

function renderContextBanner(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  if (!comp.text) return;

  const colorMap: Record<string, string> = {
    navy: t.colors.dk1,
    teal: t.colors.accent3,
    orange: t.colors.accent2,
  };

  const accentColor = colorMap[comp.accentColor || 'orange'] || t.colors.accent2;
  const labelColor = colorMap[comp.labelColor || 'orange'] || t.colors.accent2;

  // Light warm background (peach tint derived from accent)
  const bgColor = comp.accentColor === 'teal' ? 'EDF5F7' :
                  comp.accentColor === 'navy' ? 'EEF1F4' : 'FDF2EA';

  // Background strip
  s.addShape('rect', {
    x: r.x, y: r.y, w: r.w, h: r.h,
    fill: { color: bgColor },
    line: { type: 'none' }
  });

  // Left accent bar
  s.addShape('rect', {
    x: r.x, y: r.y, w: 0.05, h: r.h,
    fill: { color: accentColor },
    line: { type: 'none' }
  });

  // Build text array: optional bold label + main text
  const label = comp.label || '';
  const textParts: any[] = [];

  if (label) {
    textParts.push({
      text: label + ' ',
      options: { bold: true, fontSize: 12, color: labelColor, fontFace: 'Calibri' }
    });
  }

  textParts.push({
    text: comp.text,
    options: { fontSize: 11, color: t.colors.dk1, fontFace: 'Calibri' }
  });

  s.addText(textParts, {
    x: r.x + 0.3,
    y: r.y,
    w: r.w - 0.5,
    h: r.h,
    align: 'left',
    valign: 'middle',
    wrap: true,
    margin: 0
  });
}

function renderCalloutBar(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  if (!comp.text) return;

  let text = comp.text;
  let fontSize = 14;

  // Dynamic font sizing based on length
  if (text.length > 140) {
    fontSize = 11;
    // Truncate with ellipsis if still too long
    if (text.length > 180) {
      text = text.substring(0, 177) + '...';
    }
  } else if (text.length > 100) {
    fontSize = 12;
  }

  // Orange accent stripe on top — draws the eye to the callout as a "landing zone"
  const accentH = 0.035;
  s.addShape('rect', { x: r.x, y: r.y, w: r.w, h: accentH, fill: { color: t.colors.accent2 }, line: { type: 'none' } });

  // Main callout background — navy, slightly inset below accent
  const barY = r.y + accentH;
  const barH = r.h - accentH;
  s.addShape('rect', { x: r.x, y: barY, w: r.w, h: barH, fill: { color: t.colors.dk1 }, line: { type: 'none' } });

  // Left accent bar — vertical orange stripe for visual anchoring
  const leftBarW = 0.06;
  s.addShape('rect', { x: r.x, y: barY, w: leftBarW, h: barH, fill: { color: t.colors.accent2 }, line: { type: 'none' } });

  // Callout text — slightly larger, with more left padding to clear accent bar
  s.addText(text, {
    x: r.x + 0.35,
    y: barY,
    w: r.w - 0.55,
    h: barH,
    fontSize,
    bold: true,
    color: t.colors.lt1,
    fontFace: 'Calibri',
    align: 'left',
    valign: 'middle',
    wrap: true
  });
}

function renderTimelineTrack(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const milestones = comp.milestones || [];
  if (milestones.length === 0) return;
  const trackY = r.y + r.h * 0.4;
  const startX = r.x + 0.5;
  const endX = r.x + r.w - 0.5;
  const totalW = endX - startX;
  s.addShape('rect', { x: startX, y: trackY, w: totalW, h: 0.04, fill: { color: t.colors.dk1 }, line: { type: 'none' } });
  milestones.forEach((ms: any, i: number) => {
    const x = startX + (totalW / Math.max(milestones.length - 1, 1)) * i;
    s.addShape('ellipse', { x: x - 0.15, y: trackY - 0.15, w: 0.3, h: 0.3, fill: { color: t.colors.lt1 }, line: { color: t.colors.dk1, width: 3 } });
    s.addText(ms.date, { x: x - 0.8, y: trackY - 0.7, w: 1.6, h: 0.35, fontSize: 10, bold: true, color: t.colors.accent2, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(ms.title, { x: x - 0.8, y: trackY + 0.3, w: 1.6, h: 0.3, fontSize: 11, bold: true, color: t.colors.dk1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(ms.description, { x: x - 0.8, y: trackY + 0.65, w: 1.6, h: 0.5, fontSize: 9, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'top' });
  });
}

function renderIconGrid(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const blocks = comp.blocks || [];
  if (blocks.length === 0) return;
  const cols = blocks.length <= 4 ? 2 : 3;
  const rows = Math.ceil(blocks.length / cols);
  const gap = 0.25;
  const blockW = (r.w - (cols - 1) * gap) / cols;
  const blockH = (r.h - (rows - 1) * gap) / rows;
  blocks.forEach((block: any, i: number) => {
    const row = Math.floor(i / cols);
    const col = i % cols;
    const x = r.x + col * (blockW + gap);
    const y = r.y + row * (blockH + gap);
    s.addShape('rect', { x, y, w: blockW, h: blockH, fill: { color: t.colors.lt2 }, line: { type: 'none' }, rectRadius: 0.05 });
    s.addShape('ellipse', { x: x + blockW / 2 - 0.3, y: y + 0.15, w: 0.6, h: 0.6, fill: { color: t.colors.dk1 } });
    // Replace lightning emoji with bullet for PowerPoint compatibility
    const iconText = block.icon || '\u2022';
    s.addText(iconText, { x: x + blockW / 2 - 0.3, y: y + 0.15, w: 0.6, h: 0.6, fontSize: 16, color: t.colors.lt1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(block.title, { x: x + 0.1, y: y + 0.85, w: blockW - 0.2, h: 0.3, fontSize: 12, bold: true, color: t.colors.dk1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
    s.addText(block.description, { x: x + 0.1, y: y + 1.15, w: blockW - 0.2, h: blockH - 1.3, fontSize: 10, color: t.colors.dk1, fontFace: 'Calibri', align: 'center', valign: 'top' });
  });
}

function renderScreenshot(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  s.addShape('rect', { x: r.x, y: r.y, w: r.w, h: r.h, fill: { color: t.colors.lt2 }, line: { color: t.colors.accent1, width: 1, dashType: 'dash' } });
  s.addText(comp.placeholderText || comp.caption || '[Screenshot / Image]', { x: r.x, y: r.y + r.h / 2 - 0.25, w: r.w, h: 0.5, fontSize: 12, color: t.colors.accent1, fontFace: 'Calibri', align: 'center', valign: 'middle' });
}

function renderTextBlock(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const headingColor = getColorHex(comp.headingColor || 'navy', t);
  let offsetY = 0;
  if (comp.heading) {
    s.addShape('rect', { x: r.x, y: r.y, w: r.w, h: 0.4, fill: { color: headingColor } });
    s.addText(comp.heading, { x: r.x + 0.15, y: r.y, w: r.w - 0.3, h: 0.4, fontSize: 13, bold: true, color: t.colors.lt1, fontFace: 'Calibri', align: 'left', valign: 'middle' });
    offsetY = 0.45;
  }
  s.addShape('rect', { x: r.x, y: r.y + offsetY, w: r.w, h: r.h - offsetY, fill: { color: t.colors.lt2 }, line: { type: 'none' } });
  s.addText(comp.text || '', { x: r.x + 0.15, y: r.y + offsetY + 0.1, w: r.w - 0.3, h: r.h - offsetY - 0.2, fontSize: 12, color: t.colors.dk1, fontFace: 'Calibri', align: 'left', valign: 'top' });
}

function renderComparisonBars(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const bars = comp.bars || [];
  if (bars.length === 0) return;

  const color = getColorHex(comp.accentColor, t);
  const labelValueHeight = 0.25;  // Height for label/value row
  const barHeight = 0.25;  // Actual bar height
  const barSpacing = 0.25;  // Gap between bars

  let currentY = r.y + 0.15;  // Start padding

  bars.forEach((bar: any) => {
    // Label on LEFT and Value on RIGHT (same row)
    s.addText(bar.label, {
      x: r.x,
      y: currentY,
      w: r.w * 0.6,  // 60% of width for label
      h: labelValueHeight,
      fontSize: 11,
      bold: true,
      color: t.colors.dk1,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });

    s.addText(bar.value, {
      x: r.x + r.w * 0.6,  // Start at 60% width
      y: currentY,
      w: r.w * 0.4,  // 40% of width for value
      h: labelValueHeight,
      fontSize: 14,
      bold: true,
      color,
      fontFace: 'Calibri',
      align: 'right',
      valign: 'middle'
    });

    // Annotation below label (if present)
    let annotationHeight = 0;
    if (bar.annotation) {
      annotationHeight = 0.15;
      s.addText(bar.annotation, {
        x: r.x,
        y: currentY + labelValueHeight,
        w: r.w * 0.6,
        h: annotationHeight,
        fontSize: 9,
        italic: true,
        color: t.colors.accent1,
        fontFace: 'Calibri',
        align: 'left',
        valign: 'top'
      });
    }

    // Bar BELOW label/value/annotation
    const barY = currentY + labelValueHeight + annotationHeight + 0.05;

    // Bar background
    s.addShape('rect', {
      x: r.x,
      y: barY,
      w: r.w,
      h: barHeight,
      fill: { color: t.colors.lt2 },
      line: { type: 'none' }
    });

    // Bar fill (percentage)
    const fillW = r.w * (bar.percent / 100);
    s.addShape('rect', {
      x: r.x,
      y: barY,
      w: fillW,
      h: barHeight,
      fill: { color },
      line: { type: 'none' }
    });

    currentY = barY + barHeight + barSpacing;
  });

  // Callout box at bottom
  if (comp.callout) {
    const calloutY = currentY;
    const calloutH = 0.4;
    s.addShape('rect', {
      x: r.x,
      y: calloutY,
      w: r.w,
      h: calloutH,
      fill: { color: `${color}20` },
      line: { color, width: 3, type: 'solid' }
    });
    s.addText(comp.callout, {
      x: r.x + 0.15,
      y: calloutY,
      w: r.w - 0.3,
      h: calloutH,
      fontSize: 12,
      bold: true,
      color,
      fontFace: 'Calibri',
      align: 'left',
      valign: 'middle'
    });
  }
}

function renderWaterfallChart(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const bars = comp.bars || [];
  if (bars.length === 0) return;

  // Calculate cumulative values
  let cumulative = 0;
  const processedBars = bars.map((bar: any) => {
    const isFirst = bar.value > 0 && !bar.delta;
    const isTotal = bar.isTotal;

    if (isFirst) {
      cumulative = bar.value;
      return { ...bar, startValue: 0, endValue: bar.value, cumulative };
    } else if (isTotal) {
      return { ...bar, startValue: 0, endValue: bar.value, cumulative: bar.value };
    } else {
      const delta = bar.delta || 0;
      const startValue = cumulative;
      cumulative += delta;
      return { ...bar, startValue, endValue: cumulative, cumulative, delta };
    }
  });

  // Find max value for scaling
  const allValues = processedBars.flatMap((b: any) => [b.startValue, b.endValue]);
  const maxValue = Math.max(...allValues, 0);
  const minValue = Math.min(...allValues, 0);
  const range = maxValue - minValue;

  // Chart dimensions
  const chartH = r.h - 0.8;  // Leave space for labels
  const chartW = r.w - 0.5;
  const chartX = r.x + 0.25;
  const chartY = r.y + 0.2;
  const baseY = chartY + chartH;

  const barW = (chartW / bars.length) * 0.7;
  const gap = (chartW / bars.length) * 0.3;

  // Draw bars
  processedBars.forEach((bar: any, i: number) => {
    const x = chartX + i * (barW + gap);
    const isFirst = i === 0;
    const isTotal = bar.isTotal;
    const delta = bar.delta || 0;

    // Calculate bar position and height
    const startY = baseY - (bar.startValue / maxValue) * chartH;
    const endY = baseY - (bar.endValue / maxValue) * chartH;
    const barHeight = Math.abs(endY - startY);
    const barTop = Math.min(startY, endY);

    // Bar color
    const isPositive = delta > 0;
    const barColor = isTotal || isFirst ? t.colors.dk1 : isPositive ? t.colors.accent3 : t.colors.accent5;

    // Draw bar
    s.addShape('rect', {
      x, y: barTop, w: barW, h: Math.max(barHeight, 0.05),
      fill: { color: barColor }, line: { color: t.colors.dk1, width: 0.5 }
    });

    // Connector line to next bar
    if (comp.showConnectors && i < processedBars.length - 1) {
      s.addShape('line', {
        x, y: endY, w: barW + gap, h: 0,
        line: { color: t.colors.accent1, width: 1, dashType: 'dash' }
      });
    }

    // Value label on top of bar
    const valueText = isFirst || isTotal
      ? `$${bar.endValue}M`
      : (delta > 0 ? `+$${delta}M` : `$${delta}M`);

    s.addText(valueText, {
      x, y: barTop - 0.25, w: barW, h: 0.2,
      fontSize: 9, bold: true, color: t.colors.dk1,
      fontFace: 'Calibri', align: 'center', valign: 'middle'
    });

    // Bar label at bottom
    s.addText(bar.label, {
      x, y: baseY + 0.05, w: barW, h: 0.3,
      fontSize: 8, color: t.colors.dk1, fontFace: 'Calibri',
      align: 'center', valign: 'top', breakLine: true
    });

    // Delta label inside bar if provided and space available
    if (bar.deltaLabel && barHeight > 0.3) {
      s.addText(bar.deltaLabel, {
        x, y: barTop + barHeight / 2 - 0.1, w: barW, h: 0.2,
        fontSize: 7, bold: true, color: 'FFFFFF',
        fontFace: 'Calibri', align: 'center', valign: 'middle'
      });
    }
  });

  // Render annotations
  const annotations = comp.annotations || [];
  annotations.forEach((ann: any) => {
    const targetIndex = ann.targetBar;
    if (targetIndex >= processedBars.length) return;

    const bar = processedBars[targetIndex];
    const x = chartX + targetIndex * (barW + gap);
    const barHeight = Math.abs(baseY - (bar.endValue / maxValue) * chartH - (baseY - (bar.startValue / maxValue) * chartH));
    const barTop = baseY - Math.max(bar.startValue, bar.endValue) / maxValue * chartH;
    const annColor = ann.color === 'orange' ? t.colors.accent2 : t.colors.accent3;

    if (ann.side === 'above') {
      // Connector line
      s.addShape('rect', {
        x: x + barW / 2 - 0.01, y: barTop - 0.35, w: 0.02, h: 0.3,
        fill: { color: annColor }, line: { type: 'none' }
      });

      // Annotation box
      s.addShape('rect', {
        x: x - 0.3, y: barTop - 0.65, w: barW + 0.6, h: 0.28,
        fill: { color: annColor }, line: { type: 'none' }
      });

      s.addText(ann.text, {
        x: x - 0.25, y: barTop - 0.65, w: barW + 0.5, h: 0.28,
        fontSize: 8, bold: true, color: 'FFFFFF', fontFace: 'Calibri',
        align: 'center', valign: 'middle'
      });
    }
  });
}

function renderTeamStructure(s: any, comp: any, r: LayoutRect, t: DeckTheme) {
  const teams = comp.teams || [];
  if (teams.length === 0) return;

  // Divider line above team section
  s.addShape('rect', {
    x: r.x, y: r.y, w: r.w, h: 0.015,
    fill: { color: t.colors.accent1 }, line: { type: 'none' }
  });

  const teamAreaY = r.y + 0.1;
  const teamAreaH = r.h - 0.1;

  // Background
  s.addShape('rect', {
    x: r.x, y: teamAreaY, w: r.w, h: teamAreaH,
    fill: { color: 'F8FAFB' }, line: { type: 'none' }
  });

  // Connector symbol between teams (e.g. "+")
  const connector = comp.connector || '+';

  // Calculate layout: distribute teams evenly with space for connectors
  const teamW = (r.w - 1.0) / teams.length;
  const connectorW = teams.length > 1 ? 1.0 / (teams.length - 1) : 0;

  teams.forEach((team: any, i: number) => {
    const x = r.x + i * (teamW + (i > 0 ? connectorW : 0));

    // Person icon circle
    s.addShape('ellipse', {
      x: x + teamW / 2 - 0.4,
      y: teamAreaY + 0.15,
      w: 0.8, h: 0.8,
      fill: { color: t.colors.dk1 }
    });
    const iconText = team.icon || '\u{1F464}';
    s.addText(iconText, {
      x: x + teamW / 2 - 0.4,
      y: teamAreaY + 0.15,
      w: 0.8, h: 0.8,
      fontSize: 20, color: t.colors.lt1,
      fontFace: 'Calibri', align: 'center', valign: 'middle'
    });

    // Team name
    s.addText(team.name, {
      x, y: teamAreaY + 1.05, w: teamW, h: 0.35,
      fontSize: 13, bold: true, color: t.colors.dk1,
      fontFace: 'Calibri', align: 'center', valign: 'middle'
    });

    // Sections (heading + bullets) - positioned to the right of icon
    let sectionY = teamAreaY + 0.15;
    const sectionX = x + teamW / 2 + 0.5;
    const sectionW = teamW / 2 - 0.6;

    (team.sections || []).forEach((section: any) => {
      s.addText(section.heading, {
        x: sectionX, y: sectionY, w: sectionW, h: 0.25,
        fontSize: 11, bold: true, color: t.colors.dk1,
        fontFace: 'Calibri', align: 'left', valign: 'middle'
      });
      sectionY += 0.28;

      const bullets = (section.items || []).map((b: string) => ({ text: b, options: {} }));
      const bulletH = bullets.length * 0.22;
      if (bullets.length > 0) {
        s.addText(bullets, {
          x: sectionX, y: sectionY, w: sectionW, h: bulletH,
          fontSize: 10, color: t.colors.dk1, fontFace: 'Calibri',
          bullet: { type: 'bullet', characterCode: '2022',
            color: t.colors.accent1 },
          lineSpacing: 12, valign: 'top', italic: true
        });
        sectionY += bulletH + 0.15;
      }
    });

    // Connector "+" between teams
    if (i < teams.length - 1) {
      const connX = x + teamW + connectorW / 2 - 0.2;
      s.addText(connector, {
        x: connX, y: teamAreaY + teamAreaH / 2 - 0.25,
        w: 0.4, h: 0.5,
        fontSize: 24, bold: true, color: t.colors.accent1,
        fontFace: 'Calibri', align: 'center', valign: 'middle'
      });
    }
  });
}

// ─── SPECIAL SLIDE RENDERERS ──────────────────────────────────

function renderDirectionProofSlide(s: any, slideData: any, t: DeckTheme) {
  // 1. Title at y:0.15
  addTitleWithDivider(s, slideData, t, 0.15);
  
  // 2. Direction Banner at y:1.4, h:0.5
  addDirectionBanner(s, slideData.bannerLeft || '', slideData.bannerRight || '', t);
  
  // 3. THREE COLUMNS (x:0.75, y:2.05, each w:2.8, gap:0.15)
  const columns = slideData.columns || [];
  const colStartX = 0.75;
  const colStartY = 2.05;
  const colW = 2.8;
  const colGap = 0.15;
  const headerH = 0.55;
  const contentH = 3.0;
  const totalColH = headerH + contentH;
  
  columns.forEach((col: any, i: number) => {
    const x = colStartX + i * (colW + colGap);
    const isWinner = col.highlight === true;
    
    // Sublabel above header (Foundation, Enablement, Highest impact)
    const sublabelY = colStartY - 0.25;
    const sublabelColor = isWinner ? t.colors.accent2 : '9CA3AF'; // Orange for winner, gray for others
    const sublabelText = col.sublabel || (isWinner ? 'Highest impact' : i === 0 ? 'Foundation' : 'Enablement');
    s.addText(sublabelText, { 
      x, 
      y: sublabelY, 
      w: colW, 
      h: 0.2, 
      fontSize: 10, 
      color: sublabelColor, 
      fontFace: 'Calibri', 
      align: 'center', 
      valign: 'middle' 
    });
    
    // Winner column: thin orange border around entire column
    if (isWinner) {
      s.addShape('rect', { 
        x, 
        y: colStartY, 
        w: colW, 
        h: totalColH, 
        fill: { color: 'FFFFFF', transparency: 100 }, // No fill, just border
        line: { color: t.colors.accent2, width: 2 } 
      });
    }
    
    // Header rect
    const headerColor = isWinner ? t.colors.accent2 : '4A6B7A'; // Orange for winner, muted navy for others
    s.addShape('rect', { 
      x, 
      y: colStartY, 
      w: colW, 
      h: headerH, 
      fill: { color: headerColor }, 
      line: { type: 'none' } 
    });
    
    // Header text
    s.addText(col.header, { 
      x: x + 0.1, 
      y: colStartY, 
      w: colW - 0.2, 
      h: headerH, 
      fontSize: 12, 
      bold: true, 
      color: t.colors.lt1, 
      fontFace: 'Calibri', 
      align: 'center', 
      valign: 'middle' 
    });
    
    // Content area
    const contentY = colStartY + headerH;
    const contentBgColor = isWinner ? 'FFFFFF' : 'EEF4F7'; // White for winner, light blue for others
    s.addShape('rect', { 
      x, 
      y: contentY, 
      w: colW, 
      h: contentH, 
      fill: { color: contentBgColor }, 
      line: { type: 'none' } 
    });
    
    // Bullets
    const bullets = (col.bullets || []).slice(0, 6).map((b: string) => ({ text: b, options: {} }));
    if (bullets.length > 0) {
      s.addText(bullets, { 
        x: x + 0.15, 
        y: contentY + 0.1, 
        w: colW - 0.3, 
        h: contentH - 0.2, 
        fontSize: 11, 
        color: t.colors.dk1, 
        fontFace: 'Calibri', 
        bullet: { type: 'bullet', characterCode: '2022', color: t.colors.dk1 }, 
        lineSpacing: 14, 
        valign: 'top' 
      });
    }
  });
  
  // 4. RIGHT PROOF PANEL (x:9.1, y:2.05, w:3.483)
  const proof = slideData.proof || {};
  const proofX = 9.1;
  const proofY = 2.05;
  const proofW = 3.483;
  
  // Header text
  let currentY = proofY;
  if (proof.header) {
    s.addText(proof.header, { 
      x: proofX, 
      y: currentY, 
      w: proofW, 
      h: 0.3, 
      fontSize: 11, 
      bold: true, 
      color: t.colors.dk1, 
      fontFace: 'Calibri', 
      align: 'left', 
      valign: 'middle' 
    });
    currentY += 0.35;
  }
  
  // Subtitle
  if (proof.subtitle) {
    s.addText(proof.subtitle, { 
      x: proofX, 
      y: currentY, 
      w: proofW, 
      h: 0.25, 
      fontSize: 10, 
      color: '9CA3AF', 
      fontFace: 'Calibri', 
      align: 'left', 
      valign: 'middle', 
      italic: true 
    });
    currentY += 0.35;
  }
  
  // Two column grid for comparisons
  const comparisons = proof.comparisons || [];
  if (comparisons.length > 0) {
    // Column headers: "Realization" | "EBITDA Impact"
    const colHeaderY = currentY;
    const metricColW = 1.6;
    const metricGap = 0.1;
    
    s.addText(comparisons[0]?.metric1 || 'Realization', { 
      x: proofX, 
      y: colHeaderY, 
      w: metricColW, 
      h: 0.2, 
      fontSize: 10, 
      color: '9CA3AF', 
      fontFace: 'Calibri', 
      align: 'center', 
      valign: 'middle' 
    });
    
    s.addText(comparisons[0]?.metric2 || 'EBITDA Impact', { 
      x: proofX + metricColW + metricGap, 
      y: colHeaderY, 
      w: metricColW, 
      h: 0.2, 
      fontSize: 10, 
      color: '9CA3AF', 
      fontFace: 'Calibri', 
      align: 'center', 
      valign: 'middle' 
    });
    
    currentY += 0.25;
    
    // Comparison rows
    comparisons.forEach((comp: any, idx: number) => {
      const isHighlight = comp.highlight === true;
      const bgColor = isHighlight ? t.colors.accent3 : '6B7280'; // Teal for target, gray for current
      const textColor = 'FFFFFF'; // White text on both
      const labelColor = isHighlight ? 'D1F0F5' : 'D1D5DB'; // Light teal for target, light gray for current
      const rowH = 0.7;
      const rowY = currentY;
      
      // Left metric rect
      s.addShape('rect', { 
        x: proofX, 
        y: rowY, 
        w: metricColW, 
        h: rowH, 
        fill: { color: bgColor }, 
        line: { type: 'none' } 
      });
      
      // Left value text (18pt white bold)
      s.addText(comp.value1, { 
        x: proofX, 
        y: rowY + 0.1, 
        w: metricColW, 
        h: 0.35, 
        fontSize: 18, 
        bold: true, 
        color: textColor, 
        fontFace: 'Calibri', 
        align: 'center', 
        valign: 'middle' 
      });
      
      // Left label text (9pt light)
      s.addText(comp.label, { 
        x: proofX, 
        y: rowY + 0.45, 
        w: metricColW, 
        h: 0.2, 
        fontSize: 9, 
        color: labelColor, 
        fontFace: 'Calibri', 
        align: 'center', 
        valign: 'middle' 
      });
      
      // Right metric rect
      s.addShape('rect', { 
        x: proofX + metricColW + metricGap, 
        y: rowY, 
        w: metricColW, 
        h: rowH, 
        fill: { color: bgColor }, 
        line: { type: 'none' } 
      });
      
      // Right value text (18pt white bold)
      s.addText(comp.value2, { 
        x: proofX + metricColW + metricGap, 
        y: rowY + 0.1, 
        w: metricColW, 
        h: 0.35, 
        fontSize: 18, 
        bold: true, 
        color: textColor, 
        fontFace: 'Calibri', 
        align: 'center', 
        valign: 'middle' 
      });
      
      // Right label text (9pt light)
      s.addText(comp.label, { 
        x: proofX + metricColW + metricGap, 
        y: rowY + 0.45, 
        w: metricColW, 
        h: 0.2, 
        fontSize: 9, 
        color: labelColor, 
        fontFace: 'Calibri', 
        align: 'center', 
        valign: 'middle' 
      });
      
      currentY += rowH + 0.1;
    });
  }
  
  // Delta line: 11pt orange, right-aligned
  if (proof.delta) {
    s.addText(proof.delta, { 
      x: proofX, 
      y: currentY, 
      w: proofW, 
      h: 0.25, 
      fontSize: 11, 
      bold: true, 
      color: t.colors.accent2, // Orange
      fontFace: 'Calibri', 
      align: 'right', 
      valign: 'middle' 
    });
    currentY += 0.3;
  }
  
  // Footnote: 9pt gray italic
  if (proof.footnote) {
    s.addText(proof.footnote, { 
      x: proofX, 
      y: currentY, 
      w: proofW, 
      h: 0.25, 
      fontSize: 9, 
      color: '9CA3AF', 
      fontFace: 'Calibri', 
      align: 'left', 
      valign: 'middle', 
      italic: true 
    });
  }
  
  // 5. Optional Callout Bar at bottom
  if (slideData.calloutBar) {
    const calloutY = CALLOUT_Y;
    s.addShape('rect', { 
      x: 0.75, 
      y: calloutY, 
      w: 11.833, 
      h: 0.3, 
      fill: { color: t.colors.dk1 }, 
      line: { type: 'none' } 
    });
    s.addText(slideData.calloutBar, { 
      x: 0.95, 
      y: calloutY, 
      w: 11.433, 
      h: 0.3, 
      fontSize: 11, 
      bold: true, 
      color: t.colors.lt1, 
      fontFace: 'Calibri', 
      align: 'left', 
      valign: 'middle' 
    });
  }
}